name: ed25519_dart
description: Pure Dart implementation of Ed25519 - public-key signature system.
version: 1.0.2
homepage: https://github.com/semolex
author: Oleksii Semeshchuk <semolex@live.com>

environment:
  sdk: '<3.0.0'

dependencies:
  pointycastle:
    git:
      url: https://github.com/getcanoe/pointycastle
      ref: master

dev_dependencies:
  test:
